In [53]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mpt

In [54]:
file_path='/content/north.csv'

In [55]:
data=pd.read_csv(file_path)
data['Data']=pd.to_datetime(data['Data'])

#getting one years data
data_set=data.loc[data['Data'].dt.year == 2000]

data_set.head()

,index,Data,Hora,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),...,"VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",region,state,station,station_code,latitude,longitude,height
0,0,2000-05-09,00:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,...,-9999,-9999.0,-9999.0,N,AM,MANAUS,A101,-3.103333,-60.016389,61.25
1,1,2000-05-09,01:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,...,-9999,-9999.0,-9999.0,N,AM,MANAUS,A101,-3.103333,-60.016389,61.25
2,2,2000-05-09,02:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,...,-9999,-9999.0,-9999.0,N,AM,MANAUS,A101,-3.103333,-60.016389,61.25
3,3,2000-05-09,03:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,...,-9999,-9999.0,-9999.0,N,AM,MANAUS,A101,-3.103333,-60.016389,61.25
4,4,2000-05-09,04:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,...,-9999,-9999.0,-9999.0,N,AM,MANAUS,A101,-3.103333,-60.016389,61.25

In [56]:
#checking null values/
data_set.isnull().sum()

index                                                    0
Data                                                     0
Hora                                                     0
PRECIPITAÇÃO TOTAL, HORÁRIO (mm)                         0
PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)    0
PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)          0
PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)         0
RADIACAO GLOBAL (Kj/m²)                                  0
TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)             0
TEMPERATURA DO PONTO DE ORVALHO (°C)                     0
TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)               0
TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)               0
TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)         0
TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)         0
UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)                 0
UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)                 0
UMIDADE RELATIVA DO AR, HORARIA (%)                      0
VENTO, DIREÇÃO HORARIA (gr) (° (gr))                     0
VENTO, RAJADA MAXIMA (m/s)                               0
VENTO, VELOCIDADE HORARIA (m/s)                          0
region                                                   0
state                                                    0
station                                                  0
station_code                                             0
latitude                                                 0
longitude                                                0
height                                                   0
dtype: int64

In [69]:
#replacing -9999.0 with null values (is clearly wrong data)
data_set.replace(-9999,pd.NA)

,index,Data,Hora,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),...,"VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",region,state,station,station_code,latitude,longitude,height
0,0,2000-05-09,00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,N,AM,MANAUS,A101,-3.103333,-60.016389,61.25
1,1,2000-05-09,01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,N,AM,MANAUS,A101,-3.103333,-60.016389,61.25
2,2,2000-05-09,02:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,N,AM,MANAUS,A101,-3.103333,-60.016389,61.25
3,3,2000-05-09,03:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,N,AM,MANAUS,A101,-3.103333,-60.016389,61.25
4,4,2000-05-09,04:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,N,AM,MANAUS,A101,-3.103333,-60.016389,61.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5683,5683,2000-12-31,19:00,0.0,1003.1,1004.5,1003.1,1154.0,27.4,23.3,...,209.0,2.7,0.7,N,AM,MANAUS,A101,-3.103333,-60.016389,61.25
5684,5684,2000-12-31,20:00,0.0,1002.3,1003.1,1002.3,589.0,26.8,23.2,...,251.0,2.9,1.7,N,AM,MANAUS,A101,-3.103333,-60.016389,61.25
5685,5685,2000-12-31,21:00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,N,AM,MANAUS,A101,-3.103333,-60.016389,61.25
5686,5686,2000-12-31,22:00,0.0,1002.9,1002.9,1002.4,210.0,26.0,23.3,...,247.0,3.6,1.4,N,AM,MANAUS,A101,-3.103333,-60.016389,61.25
5687,5687,2000-12-31,23:00,0.0,1003.6,1003.6,1002.9,1.0,24.8,23.3,...,268.0,2.0,0.4,N,AM,MANAUS,A101,-3.103333,-60.016389,61.25

In [70]:
#replacing null value with mean value of the particular column
columns_fill=data_set.columns[3:20]
mean=data_set[columns_fill].mean()
data_set.loc[:, columns_fill] = data_set[columns_fill].fillna(mean)
data_set.head()

,index,Data,Hora,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),...,"VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",region,state,station,station_code,latitude,longitude,height
0,0,2000-05-09,00:00,0.146044,1003.827221,1004.115905,1003.501197,1529.583786,26.73456,22.968605,...,157.408583,4.343411,1.102612,N,AM,MANAUS,A101,-3.103333,-60.016389,61.25
1,1,2000-05-09,01:00,0.146044,1003.827221,1004.115905,1003.501197,1529.583786,26.73456,22.968605,...,157.408583,4.343411,1.102612,N,AM,MANAUS,A101,-3.103333,-60.016389,61.25
2,2,2000-05-09,02:00,0.146044,1003.827221,1004.115905,1003.501197,1529.583786,26.73456,22.968605,...,157.408583,4.343411,1.102612,N,AM,MANAUS,A101,-3.103333,-60.016389,61.25
3,3,2000-05-09,03:00,0.146044,1003.827221,1004.115905,1003.501197,1529.583786,26.73456,22.968605,...,157.408583,4.343411,1.102612,N,AM,MANAUS,A101,-3.103333,-60.016389,61.25
4,4,2000-05-09,04:00,0.146044,1003.827221,1004.115905,1003.501197,1529.583786,26.73456,22.968605,...,157.408583,4.343411,1.102612,N,AM,MANAUS,A101,-3.103333,-60.016389,61.25

In [71]:
data_set.isnull().sum()

index                                                    0
Data                                                     0
Hora                                                     0
PRECIPITAÇÃO TOTAL, HORÁRIO (mm)                         0
PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)    0
PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)          0
PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)         0
RADIACAO GLOBAL (Kj/m²)                                  0
TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)             0
TEMPERATURA DO PONTO DE ORVALHO (°C)                     0
TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)               0
TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)               0
TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)         0
TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)         0
UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)                 0
UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)                 0
UMIDADE RELATIVA DO AR, HORARIA (%)                      0
VENTO, DIREÇÃO HORARIA (gr) (° (gr))                     0
VENTO, RAJADA MAXIMA (m/s)                               0
VENTO, VELOCIDADE HORARIA (m/s)                          0
region                                                   0
state                                                    0
station                                                  0
station_code                                             0
latitude                                                 0
longitude                                                0
height                                                   0
dtype: int64

In [72]:
#dropping region,state,station_code,latitude,longitude,height since they are the same

data_set.drop(["region","state",'station','station_code','latitude','longitude','height'],axis=1)

,index,Data,Hora,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)"
0,0,2000-05-09,00:00,0.146044,1003.827221,1004.115905,1003.501197,1529.583786,26.73456,22.968605,27.285911,26.204111,23.424885,22.529555,83.967072,77.937737,81.042532,157.408583,4.343411,1.102612
1,1,2000-05-09,01:00,0.146044,1003.827221,1004.115905,1003.501197,1529.583786,26.73456,22.968605,27.285911,26.204111,23.424885,22.529555,83.967072,77.937737,81.042532,157.408583,4.343411,1.102612
2,2,2000-05-09,02:00,0.146044,1003.827221,1004.115905,1003.501197,1529.583786,26.73456,22.968605,27.285911,26.204111,23.424885,22.529555,83.967072,77.937737,81.042532,157.408583,4.343411,1.102612
3,3,2000-05-09,03:00,0.146044,1003.827221,1004.115905,1003.501197,1529.583786,26.73456,22.968605,27.285911,26.204111,23.424885,22.529555,83.967072,77.937737,81.042532,157.408583,4.343411,1.102612
4,4,2000-05-09,04:00,0.146044,1003.827221,1004.115905,1003.501197,1529.583786,26.73456,22.968605,27.285911,26.204111,23.424885,22.529555,83.967072,77.937737,81.042532,157.408583,4.343411,1.102612
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5683,5683,2000-12-31,19:00,0.000000,1003.100000,1004.500000,1003.100000,1154.000000,27.40000,23.300000,28.100000,26.900000,24.100000,23.000000,82.000000,75.000000,78.000000,209.000000,2.700000,0.700000
5684,5684,2000-12-31,20:00,0.000000,1002.300000,1003.100000,1002.300000,589.000000,26.80000,23.200000,27.400000,26.800000,23.600000,23.000000,82.000000,78.000000,81.000000,251.000000,2.900000,1.700000
5685,5685,2000-12-31,21:00,0.000000,1003.827221,1004.115905,1003.501197,1529.583786,26.73456,22.968605,27.285911,26.204111,23.424885,22.529555,83.967072,77.937737,81.042532,157.408583,4.343411,1.102612
5686,5686,2000-12-31,22:00,0.000000,1002.900000,1002.900000,1002.400000,210.000000,26.00000,23.300000,26.700000,26.000000,23.500000,23.100000,85.000000,81.000000,85.000000,247.000000,3.600000,1.400000
5687,5687,2000-12-31,23:00,0.000000,1003.600000,1003.600000,1002.900000,1.000000,24.80000,23.300000,26.000000,24.800000,23.600000,23.200000,91.000000,85.000000,91.000000,268.000000,2.000000,0.400000

In [73]:
#removing outliers using z score
from scipy import stats


def remove_outliers_zscore(df, threshold=4):

    numeric_columns = df.select_dtypes(include=['number'])
    z_scores = stats.zscore(numeric_columns)

    # z-score measures how many standard deviations a data point is from the mean.if greater than 4 then data point is an outlier
    outliers = (abs(z_scores) > threshold).any(axis=1)

    df_no_outliers = df[~outliers]

    return df_no_outliers

data_set_new = remove_outliers_zscore(data_set)

In [74]:
#standardizing data: data in each column has a mean of 0 and standard deviation of 1
#standardising columns[3:20]

columns_to_standardize=data_set_new.columns[3:20]


from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df_standardized = scaler.fit_transform(data_set_new[columns_to_standardize])

df_standardized = pd.DataFrame(df_standardized, columns=[f'{col}_standardized' for col in columns_to_standardize])

#Adding standardized values to data frame
df = pd.concat([data_set_new, df_standardized], axis=1)

# Droping original values from data frame
df.drop(columns=columns_to_standardize, inplace=True)


df.head()

,index,Data,Hora,region,state,station,station_code,latitude,longitude,height,...,TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)_standardized,TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)_standardized,TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)_standardized,TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)_standardized,UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)_standardized,UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)_standardized,"UMIDADE RELATIVA DO AR, HORARIA (%)_standardized","VENTO, DIREÇÃO HORARIA (gr) (° (gr))_standardized","VENTO, RAJADA MAXIMA (m/s)_standardized","VENTO, VELOCIDADE HORARIA (m/s)_standardized"
0,0.0,2000-05-09,00:00,N,AM,MANAUS,A101,-3.103333,-60.016389,61.25,...,-0.015652,-0.021828,-0.031321,-0.039132,0.009379,0.005071,0.009958,0.006886,0.336619,0.010265
1,1.0,2000-05-09,01:00,N,AM,MANAUS,A101,-3.103333,-60.016389,61.25,...,-0.015652,-0.021828,-0.031321,-0.039132,0.009379,0.005071,0.009958,0.006886,0.336619,0.010265
2,2.0,2000-05-09,02:00,N,AM,MANAUS,A101,-3.103333,-60.016389,61.25,...,-0.015652,-0.021828,-0.031321,-0.039132,0.009379,0.005071,0.009958,0.006886,0.336619,0.010265
3,3.0,2000-05-09,03:00,N,AM,MANAUS,A101,-3.103333,-60.016389,61.25,...,-0.015652,-0.021828,-0.031321,-0.039132,0.009379,0.005071,0.009958,0.006886,0.336619,0.010265
4,4.0,2000-05-09,04:00,N,AM,MANAUS,A101,-3.103333,-60.016389,61.25,...,-0.015652,-0.021828,-0.031321,-0.039132,0.009379,0.005071,0.009958,0.006886,0.336619,0.010265

In [ ]:
|