In [2]:
import pandas as pd
import numpy as np
import os

In [3]:
folder_path = '/content/drive/My Drive/eeg data'
file_list = os.listdir(folder_path)
files = [f for f in file_list if f.endswith('.csv')]
final_df=[]

In [9]:
for file in files:
  file_path = os.path.join(folder_path, file)
  df = pd.read_csv(file_path)
  df.columns =['Output1', 'Output2', 'Output3', 'Output4', 'var1', 'var2', 'var3', 'var4']
  df = df.iloc[:, :4]
  st_marks = ['start zero.png', 'start one.png', 'start two.jpg', 'start three.jpg', 'start four.jpg', 'start five.jpg', 'start six.jpg', 'start seven.jpg', 'start eight.jpg','start nine.jpg','start animal.jpg']
  end_marks=['end zero.png', 'end one.png', 'end two.jpg', 'end three.jpg', 'end four.jpg', 'end five.jpg', 'end six.jpg', 'end seven.jpg', 'end eight.jpg','end nine.jpg','end animal.jpg']
  df1=[]
  merged_df = pd.DataFrame()
  numerical_labels=st_marks[:-1]
  nonnum_label=st_marks[-1]



  for start,end in zip(st_marks, end_marks):
    start_idx = df[df['Output1'] ==start].index
    end_idx = df[df['Output1'] ==end].index
    temp_df=[]

    # Slice the DataFrame from start to end index
    for i,j in zip(start_idx, end_idx):
        row = df[i+1:j]
        row['numerical'] = 1 if start in numerical_labels else 0
        temp_df.append(row)
    merged_df=pd.concat(temp_df,ignore_index=True,sort=False)
    merged_df = merged_df.reset_index(drop=True)
    final_df.append(merged_df)

print(final_df)

<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['numerical'] = 1 if start in numerical_labels else 0
<ipython-input-9-6fa1574ba56a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead


[     Output1 Output2 Output3 Output4  numerical
0     197158   10561  806458  703133          1
1     196998   10522  806103  702832          1
2     196741   10531  805028  701851          1
3     196962   10609  805544  702280          1
4     197226   10629  806467  703101          1
...      ...     ...     ...     ...        ...
1275  199158   15200  816869  712238          1
1276  199255   15258  816928  712270          1
1277  199304   15263  816946  712274          1
1278  199230   15210  816909  712257          1
1279  199146   15183  816879  712249          1

[1280 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0     193746    3107  789263  688324          1
1     193809    3148  789205  688231          1
2     193709    3106  788867  687926          1
3     193659    3048  788988  688076          1
4     193679    3053  789231  688316          1
...      ...     ...     ...     ...        ...
1275  196056    8018  800756  698248          1
1276  195968    7966  800710  698234          1
1277  195906    7955  800694  698232          1
1278  195955    8004  800743  698257          1
1279  196051    8057  800803  698283          1

[1280 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0     174359  -32273  680903  592991          1
1     174349  -32302  680883  592969          1
2     174215  -32352  680674  592822          1
3     174197  -32352  680759  592924          1
4     174278  -32302  680894  593023          1
...      ...     ...     ...     ...        ...
1147  176310  -28856  693218  603623          1
1148  176394  -28829  693260  603644          1
1149  176373  -28867  693242  603638          1
1150  176278  -28911  693211  603628          1
1151  176248  -28896  693221  603642          1

[1152 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0     169834  -38259  655073  570809          1
1     169775  -38272  655062  570823          1
2     169819  -38228  655108  570859          1
3     169913  -38179  655169  570878          1
4     169929  -38195  655170  570864          1
...      ...     ...     ...     ...        ...
1531  172903  -34452  672285  585500          1
1532  172834  -34500  672249  585489          1
1533  172752  -34512  672224  585483          1
1534  172766  -34471  672260  585506          1
1535  172866  -34425  672321  585538          1

[1536 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0     181271  -20718  720091  627717          1
1     181350  -20669  720089  627666          1
2     181336  -20686  719988  627541          1
3     181291  -20743  720069  627645          1
4     181239  -20759  720089  627704          1
...      ...     ...     ...     ...        ...
1275  183550  -16719  732274  638646          1
1276  183464  -16774  732228  638646          1
1277  183417  -16776  732223  638674          1
1278  183470  -16726  732269  638708          1
1279  183557  -16679  732327  638711          1

[1280 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0     184442  -14769  738127  643814          1
1     184447  -14788  738124  643796          1
2     184363  -14844  738078  643791          1
3     184311  -14856  738067  643818          1
4     184361  -14808  738114  643849          1
...      ...     ...     ...     ...        ...
1194  186499  -10696  750106  654320          1
1195  186417  -10757  750057  654308          1
1196  186354  -10780  750038  654329          1
1197  186390  -10733  750082  654367          1
1198  186483  -10678  750148  654383          1

[1199 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0     203548   25093  838288  730978          1
1     203644   25153  838353  731008          1
2     203703   25168  838380  731019          1
3     203639   25116  838341  731009          1
4     203549   25082  838303  730998          1
...      ...     ...     ...     ...        ...
1284  205443   29637  848353  739781          1
1285  205515   29653  848384  739800          1
1286  205466   29609  848353  739788          1
1287  205368   29575  848317  739773          1
1288  205361   29598  848334  739786          1

[1289 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0     177487  -26572  700038  609794          1
1     177423  -26619  699938  609716          1
2     177304  -26657  699784  609614          1
3     177333  -26637  699938  609766          1
4     177425  -26582  700046  609833          1
...      ...     ...     ...     ...        ...
1275  179925  -22841  713294  621663          1
1276  179956  -22799  713331  621705          1
1277  180042  -22748  713396  621720          1
1278  180072  -22750  713414  621699          1
1279  180004  -22799  713371  621686          1

[1280 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0     190829   -3276  772981  674043          1
1     190771   -3326  772943  674029          1
2     190678   -3367  772904  674013          1
3     190676   -3340  772927  674031          1
4     190777   -3277  772995  674069          1
...      ...     ...     ...     ...        ...
1221  192754     971  783943  683597          1
1222  192834    1029  784006  683632          1
1223  192919    1056  784055  683634          1
1224  192889    1020  784033  683617          1
1225  192788     977  783975  683611          1

[1226 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0     187450   -8737  755854  659493          1
1     187368   -8755  755798  659454          1
2     187338   -8717  755606  659264          1
3     187253   -8669  754948  658651          1
4     187313   -8679  755081  658773          1
...      ...     ...     ...     ...        ...
1275  189562   -5104  767466  669444          1
1276  189672   -5056  767538  669466          1
1277  189723   -5073  767564  669451          1
1278  189639   -5132  767515  669430          1
1279  189550   -5145  767480  669441          1

[1280 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0     200295   17678  822345  717007          0
1     200394   17740  822409  717040          0
2     200443   17751  822436  717048          0
3     200377   17698  822390  717029          0
4     200292   17661  822359  717019          0
...      ...     ...     ...     ...        ...
1163  202281   22092  832219  725561          0
1164  202368   22149  832280  725591          0
1165  202441   22169  832313  725607          0
1166  202392   22124  832278  725594          0
1167  202295   22085  832241  725578          0

[1168 rows x 5 columns],      Output1 Output2  Output3 Output4  numerical
0     258948  108489  1014034  897196          1
1     258840  108406  1013679  896875          1
2     258558  108269  1012916  896233          1
3     258653  108346  1013398  896694          1
4     258859  108468  1013985  897198          1
...      ...     ...      ...     ...        ...
1275  261014  111998  1020345  903194          1
1276  260933  111978  1020306  903198          1
1277  260942  112014  1020328  903218          1
1278  261030  112068  1020384  903233          1
1279  261081  112066  1020408  903224          1

[1280 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0     245061   85909  972143  857936          1
1     245133   85963  972126  857887          1
2     245159   85946  972007  857750          1
3     245147   85907  972122  857875          1
4     245076   85886  972143  857934          1
...      ...     ...     ...     ...        ...
1275  247863   89876  980232  865328          1
1276  247919   89895  980263  865314          1
1277  247863   89845  980222  865291          1
1278  247776   89810  980184  865302          1
1279  247783   89836  980206  865344          1

[1280 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0     229120   57088  916230  806109          1
1     229221   57146  916294  806144          1
2     229257   57143  916306  806151          1
3     229175   57088  916256  806134          1
4     229097   57061  916231  806124          1
...      ...     ...     ...     ...        ...
1198  231483   61638  924974  814218          1
1199  231556   61691  925029  814250          1
1200  231634   61726  925073  814264          1
1201  231610   61694  925046  814257          1
1202  231518   61644  924998  814243          1

[1203 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0     220393   43056  887483  778758          1
1     220378   43021  887373  778615          1
2     220216   42951  886987  778303          1
3     220234   42975  887268  778614          1
4     220314   43038  887460  778793          1
...      ...     ...     ...     ...        ...
1275  223903   47716  897988  788694          1
1276  223823   47698  897946  788728          1
1277  223836   47738  897971  788784          1
1278  223934   47787  898044  788791          1
1279  223984   47781  898071  788751          1

[1280 rows x 5 columns],      Output1 Output2  Output3 Output4  numerical
0     255833  103239  1004236  888123          1
1     255647  103157  1003824  887806          1
2     255214  102994  1002334  886501          1
3     255106  102969  1001725  885929          1
4     255265  103024  1002049  886161          1
...      ...     ...      ...     ...        ...
1275  257886  106934  1011049  894524          1
1276  257899  106975  1011076  894553          1
1277  257988  107023  1011134  894566          1
1278  258039  107017  1011159  894552          1
1279  257975  106966  1011116  894545          1

[1280 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0     237903   74019  948656  836375          1
1     237951   74073  948637  836334          1
2     237944   74068  948312  836006          1
3     237949   74038  948361  836054          1
4     237950   74021  948681  836374          1
...      ...     ...     ...     ...        ...
1275  240496   78048  957048  843934          1
1276  240566   78074  957084  843948          1
1277  240519   78029  957053  843934          1
1278  240429   77982  957014  843923          1
1279  240421   78001  957026  843939          1

[1280 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0     249166   92142  984116  868991          1
1     249133   92088  984008  868879          1
2     248997   92018  983801  868737          1
3     249001   92051  983978  868938          1
4     249081   92116  984075  869009          1
...      ...     ...     ...     ...        ...
1275  251282   95818  990719  875432          1
1276  251190   95782  990673  875433          1
1277  251175   95799  990681  875459          1
1278  251259   95853  990739  875481          1
1279  251331   95873  990777  875472          1

[1280 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0     234131   66593  934583  823084          1
1     234158   66638  934546  823054          1
2     234146   66641  934165  822656          1
3     234206   66635  934330  822773          1
4     234200   66606  934605  823056          1
...      ...     ...     ...     ...        ...
1275  236652   71241  943716  831658          1
1276  236734   71278  943757  831659          1
1277  236702   71236  943728  831636          1
1278  236607   71184  943681  831631          1
1279  236583   71198  943690  831660          1

[1280 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0     241624   80128  961158  847698          1
1     241568   80117  961139  847697          1
2     241620   80174  961188  847726          1
3     241716   80231  961247  847756          1
4     241726   80213  961239  847754          1
...      ...     ...     ...     ...        ...
1190  243911   83996  968561  854488          1
1191  243964   84048  968608  854521          1
1192  244056   84082  968663  854507          1
1193  244060   84057  968656  854470          1
1194  243971   84006  968603  854471          1

[1195 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0     225749   50975  904078  794526          1
1     225676   50918  903983  794456          1
2     225552   50868  903797  794329          1
3     225576   50901  903889  794428          1
4     225706   50973  904075  794559          1
...      ...     ...     ...     ...        ...
1275  228207   55138  912661  802774          1
1276  228183   55145  912667  802796          1
1277  228253   55202  912724  802829          1
1278  228333   55238  912771  802832          1
1279  228306   55206  912748  802814          1

[1280 rows x 5 columns],      Output1 Output2  Output3 Output4  numerical
0     252455   97733   994425  878891          0
1     252391   97730   994356  878840          0
2     252402   97758   994213  878688          0
3     252526   97812   994399  878821          0
4     252550   97795   994488  878906          0
...      ...     ...      ...     ...        ...
1275  254828  101639  1001541  885561          0
1276  254918  101692  1001603  885576          0
1277  254973  101698  1001631  885564          0
1278  254914  101648  1001592  885547          0
1279  254834  101618  1001554  885556          0

[1280 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0     149819   -1219  539435  465914          1
1     149854   -1171  539480  465948          1
2     149906   -1102  539496  465896          1
3     149883   -1114  539400  465770          1
4     149863   -1187  539479  465884          1
...      ...     ...     ...     ...        ...
1276  153826    -249  556898  481336          1
1277  153880    -194  556952  481313          1
1278  153864    -232  556942  481299          1
1279  153803    -307  556903  481328          1
1280  153787    -314  556906  481376          1

[1281 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0     144160   -2142  513920  443393          1
1     144083   -2207  513839  443387          1
2     144016   -2194  513676  443277          1
3     144075   -2122  513726  443278          1
4     144198   -2091  513996  443448          1
...      ...     ...     ...     ...        ...
1275  148265   -1571  532318  459525          1
1276  148211   -1636  532287  459543          1
1277  148229   -1596  532324  459573          1
1278  148302   -1503  532403  459594          1
1279  148329   -1489  532426  459585          1

[1280 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0     100334    8357  299621  257600          1
1     100405    8399  299677  257603          1
2     100381    8359  299570  257467          1
3     100326    8293  299544  257470          1
4     100323    8288  299661  257628          1
...      ...     ...     ...     ...        ...
1275  105181    5615  324293  278454          1
1276  105216    5619  324328  278449          1
1277  105160    5548  324293  278441          1
1278  105104    5496  324266  278463          1
1279  105128    5533  324313  278507          1

[1280 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0     155698     181  565099  488462          1
1     155646     110  565064  488482          1
2     155634     113  565077  488506          1
3     155674     186  565109  488496          1
4     155724     239  565162  488496          1
...      ...     ...     ...     ...        ...
1190  159719    1497  580911  502181          1
1191  159651    1457  580866  502162          1
1192  159670    1504  580899  502174          1
1193  159759    1575  580983  502216          1
1194  159798    1569  581018  502242          1

[1195 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0      92506   12624  260736  223813          1
1      92491   12628  260731  223836          1
2      92535   12677  260746  223831          1
3      92598   12708  260836  223864          1
4      92581   12656  260853  223876          1
...      ...     ...     ...     ...        ...
1147   97400   10112  284576  244188          1
1148   97383   10069  284573  244176          1
1149   97302    9989  284532  244169          1
1150   97274    9979  284536  244198          1
1151   97343   10048  284604  244249          1

[1152 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0     132702   -2442  460123  396197          1
1     132621   -2524  460031  396156          1
2     132552   -2562  459933  396120          1
3     132620   -2503  460071  396239          1
4     132704   -2436  460178  396268          1
...      ...     ...     ...     ...        ...
1275  136796   -2772  479824  413314          1
1276  136740   -2827  479792  413351          1
1277  136750   -2802  479825  413400          1
1278  136818   -2728  479896  413409          1
1279  136855   -2704  479929  413385          1

[1280 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0     138438   -2744  487602  420240          1
1     138497   -2676  487627  420198          1
2     138494   -2678  487556  420081          1
3     138473   -2747  487623  420181          1
4     138431   -2787  487627  420246          1
...      ...     ...     ...     ...        ...
1275  142511   -2402  506334  436773          1
1276  142573   -2347  506393  436750          1
1277  142556   -2391  506382  436733          1
1278  142490   -2466  506335  436755          1
1279  142471   -2474  506341  436804          1

[1280 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0     113879    1604  368746  316720          1
1     113948    1681  368796  316721          1
2     113964    1688  368758  316643          1
3     113936    1619  368790  316689          1
4     113884    1564  368794  316739          1
...      ...     ...     ...     ...        ...
1275  118453     161  391219  336004          1
1276  118496     184  391261  335983          1
1277  118456     119  391238  335972          1
1278  118394      59  391206  336006          1
1279  118401      82  391229  336059          1

[1280 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0     126647   -1857  431759  371416          1
1     126673   -1807  431771  371416          1
2     126728   -1747  431771  371358          1
3     126763   -1759  431863  371417          1
4     126709   -1836  431848  371442          1
...      ...     ...     ...     ...        ...
1275  130932   -2382  452066  389222          1
1276  131002   -2312  452131  389219          1
1277  131029   -2298  452163  389193          1
1278  130979   -2370  452128  389192          1
1279  130928   -2418  452109  389242          1

[1280 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0     120233    -382  399930  343639          1
1     120169    -425  399854  343626          1
2     120126    -390  399686  343476          1
3     120258    -319  399938  343638          1
4     120304    -325  400041  343691          1
...      ...     ...     ...     ...        ...
1275  124472   -1487  421098  362151          1
1276  124479   -1470  421120  362178          1
1277  124552   -1392  421196  362209          1
1278  124591   -1364  421240  362208          1
1279  124548   -1428  421214  362207          1

[1280 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0     107045    4586  333996  286743          0
1     107009    4568  333975  286748          0
2     107039    4618  333977  286731          0
3     107108    4671  334052  286754          0
4     107123    4643  334113  286798          0
...      ...     ...     ...     ...        ...
1275  111613    2514  357200  306770          0
1276  111666    2578  357262  306815          0
1277  111734    2634  357326  306829          0
1278  111723    2596  357326  306817          0
1279  111656    2519  357293  306817          0

[1280 rows x 5 columns],      Output1 Output2 Output3 Output4  numerical
0     362717  298041  698809  714887          1

In [6]:
final_combined_df = pd.concat(final_df, ignore_index=True, sort=False)

print(final_combined_df)

       Output1 Output2 Output3 Output4  numerical
0       197158   10561  806458  703133          1
1       196998   10522  806103  702832          1
2       196741   10531  805028  701851          1
3       196962   10609  805544  702280          1
4       197226   10629  806467  703101          1
...        ...     ...     ...     ...        ...
250793  325782  249311  797428  707219          0
250794  325839  249354  797467  707268          0
250795  326102  249544  797623  707372          0
250796  326178  249604  797673  707388          0
250797  326025  249493  797593  707326          0

[250798 rows x 5 columns]

In [8]:
numerical_data=final_combined_df[final_combined_df['numerical']==1]
nonnum_data=final_combined_df[final_combined_df['numerical']==0]
from sklearn.utils import resample
nonnum_upsampled = resample(nonnum_data,
                                   replace=True,
                                   n_samples=len(numerical_data),
                                   random_state=42)
new_data=pd.concat([numerical_data,nonnum_upsampled])
new_data=new_data.sample(frac=1,random_state=42).reset_index(drop=True)
print(new_data)

       Output1 Output2  Output3  Output4  numerical
0       296055  418068  2071707  2032176          0
1       204424   53570   430976   333958          1
2       471974  251606   827053   639794          1
3       200584   18067   823164   717666          0
4       482533  364449  1177463  1010651          0
...        ...     ...      ...      ...        ...
456137  200466   17898   822861   717436          0
456138  221711   63338   479240   369039          0
456139  313129  120577    86722    58069          1
456140  377351  116439    91723    48833          1
456141  286486  141136    96962    78726          1

[456142 rows x 5 columns]

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
sc=StandardScaler()
X=new_data.drop(columns=['numerical']).values
y=new_data['numerical'].values
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2,random_state=42)

X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
X_train = np.expand_dims(X_train, axis=2)
X_test = np.expand_dims(X_test, axis=2)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(364913, 4, 1)
(91229, 4, 1)
(364913,)
(91229,)

In [15]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv1D, MaxPooling1D,Flatten, Dropout

model = Sequential([
    Conv1D(filters=32, kernel_size=4, activation='relu', input_shape=(4, 1)),
    Flatten(),
    Dense(32, activation='relu'),
    Dropout(0.5),
    Dense(1, activation='sigmoid')
])
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
history=model.fit(X_train, y_train, epochs=20, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/20
11404/11404 [==============================] - 34s 3ms/step - loss: 0.5401 - accuracy: 0.7044 - val_loss: 0.3293 - val_accuracy: 0.8669
Epoch 2/20
11404/11404 [==============================] - 30s 3ms/step - loss: 0.3281 - accuracy: 0.8432 - val_loss: 0.2469 - val_accuracy: 0.8766
Epoch 3/20
11404/11404 [==============================] - 31s 3ms/step - loss: 0.2807 - accuracy: 0.8632 - val_loss: 0.2114 - val_accuracy: 0.8980
Epoch 4/20
11404/11404 [==============================] - 29s 3ms/step - loss: 0.2598 - accuracy: 0.8718 - val_loss: 0.1934 - val_accuracy: 0.9055
Epoch 5/20
11404/11404 [==============================] - 29s 3ms/step - loss: 0.2474 - accuracy: 0.8758 - val_loss: 0.1955 - val_accuracy: 0.9048
Epoch 6/20
11404/11404 [==============================] - 29s 3ms/step - loss: 0.2442 - accuracy: 0.8770 - val_loss: 0.1888 - val_accuracy: 0.9105
Epoch 7/20
11404/11404 [==============================] - 29s 3ms/step - loss: 0.2354 - accuracy: 0.8806 - val_loss: 0.1671 - val_accuracy: 0.9198
Epoch 8/20
11404/11404 [==============================] - 29s 3ms/step - loss: 0.2321 - accuracy: 0.8817 - val_loss: 0.1670 - val_accuracy: 0.9215
Epoch 9/20
11404/11404 [==============================] - 29s 3ms/step - loss: 0.2305 - accuracy: 0.8820 - val_loss: 0.1627 - val_accuracy: 0.9123
Epoch 10/20
11404/11404 [==============================] - 29s 3ms/step - loss: 0.2246 - accuracy: 0.8848 - val_loss: 0.1622 - val_accuracy: 0.9198
Epoch 11/20
11404/11404 [==============================] - 29s 3ms/step - loss: 0.2259 - accuracy: 0.8835 - val_loss: 0.1841 - val_accuracy: 0.8865
Epoch 12/20
11404/11404 [==============================] - 30s 3ms/step - loss: 0.2221 - accuracy: 0.8858 - val_loss: 0.1545 - val_accuracy: 0.9346
Epoch 13/20
11404/11404 [==============================] - 28s 2ms/step - loss: 0.2216 - accuracy: 0.8857 - val_loss: 0.1478 - val_accuracy: 0.9209
Epoch 14/20
11404/11404 [==============================] - 29s 3ms/step - loss: 0.2198 - accuracy: 0.8859 - val_loss: 0.1527 - val_accuracy: 0.9255
Epoch 15/20
11404/11404 [==============================] - 28s 2ms/step - loss: 0.2159 - accuracy: 0.8881 - val_loss: 0.1439 - val_accuracy: 0.9239
Epoch 16/20
11404/11404 [==============================] - 28s 2ms/step - loss: 0.2180 - accuracy: 0.8860 - val_loss: 0.1435 - val_accuracy: 0.9300
Epoch 17/20
11404/11404 [==============================] - 29s 3ms/step - loss: 0.2114 - accuracy: 0.8907 - val_loss: 0.1580 - val_accuracy: 0.9229
Epoch 18/20
11404/11404 [==============================] - 28s 2ms/step - loss: 0.2131 - accuracy: 0.8887 - val_loss: 0.1502 - val_accuracy: 0.9253
Epoch 19/20
11404/11404 [==============================] - 28s 2ms/step - loss: 0.2170 - accuracy: 0.8881 - val_loss: 0.1426 - val_accuracy: 0.9338
Epoch 20/20
11404/11404 [==============================] - 30s 3ms/step - loss: 0.2172 - accuracy: 0.8888 - val_loss: 0.1680 - val_accuracy: 0.9087

In [16]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)

2851/2851 [==============================] - 4s 2ms/step - loss: 0.1680 - accuracy: 0.9087
Test Loss: 0.16796621680259705
Test Accuracy: 0.9087132215499878

In [17]:
from sklearn.metrics import confusion_matrix,precision_score,f1_score
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
precision = precision_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
print("Confusion Matrix:")
print(cm)
print("Precision:", precision)
print("F1 Score:", f1)

2851/2851 [==============================] - 5s 2ms/step
Confusion Matrix:
[[42432  3261]
 [ 5067 40469]]
Precision: 0.9254287674365425
F1 Score: 0.9067058006407815